language: node_js

node_js:
  - "node"

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test

after_success:
  - yarn run build

deploy:
  provider: script
  script: yarn run deploy
  skip_cleanup: true
  on:
    branch: master
